"""Published API contracts; source revisions are recorded in tests/parity-audit.json."""

TASK_PATH = "/happyhorse/tasks"

ENDPOINTS = {
    "happyhorse_generate_video": {
        "method": "POST",
        "path": "/happyhorse/videos",
        "operation": "generate",
        "schema": {
            "type": "object",
            "properties": {
                "action": {
                    "enum": ["generate", "image_to_video", "reference_to_video", "video_edit"],
                    "type": "string",
                },
                "model": {
                    "enum": [
                        "happyhorse-1.0-t2v",
                        "happyhorse-1.1-t2v",
                        "happyhorse-1.0-i2v",
                        "happyhorse-1.1-i2v",
                        "happyhorse-1.0-r2v",
                        "happyhorse-1.1-r2v",
                        "happyhorse-1.0-video-edit",
                    ],
                    "type": "string",
                },
                "prompt": {"type": "string"},
                "image_url": {"type": "string"},
                "image_urls": {"type": "array", "items": {"type": "string"}},
                "video_url": {"type": "string"},
                "resolution": {"enum": ["720P", "1080P"], "type": "string"},
                "ratio": {"enum": ["16:9", "9:16", "1:1", "4:3", "3:4"], "type": "string"},
                "duration": {"type": "integer", "minimum": 3, "maximum": 15},
                "watermark": {"type": "boolean"},
                "audio_setting": {"enum": ["auto", "origin"], "type": "string"},
                "seed": {"type": "integer", "minimum": 0, "maximum": 2147483647},
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
            },
        },
        "properties": {
            "action": {
                "enum": ["generate", "image_to_video", "reference_to_video", "video_edit"],
                "type": "string",
            },
            "model": {
                "enum": [
                    "happyhorse-1.0-t2v",
                    "happyhorse-1.1-t2v",
                    "happyhorse-1.0-i2v",
                    "happyhorse-1.1-i2v",
                    "happyhorse-1.0-r2v",
                    "happyhorse-1.1-r2v",
                    "happyhorse-1.0-video-edit",
                ],
                "type": "string",
            },
            "prompt": {"type": "string"},
            "image_url": {"type": "string"},
            "image_urls": {"type": "array", "items": {"type": "string"}},
            "video_url": {"type": "string"},
            "resolution": {"enum": ["720P", "1080P"], "type": "string"},
            "ratio": {"enum": ["16:9", "9:16", "1:1", "4:3", "3:4"], "type": "string"},
            "duration": {"type": "integer", "minimum": 3, "maximum": 15},
            "watermark": {"type": "boolean"},
            "audio_setting": {"enum": ["auto", "origin"], "type": "string"},
            "seed": {"type": "integer", "minimum": 0, "maximum": 2147483647},
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {"action": "generate", "resolution": "720P", "duration": 3, "ratio": "16:9"},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "happyhorse_task_retrieve": {
        "method": "POST",
        "path": "/happyhorse/tasks",
        "operation": "task",
        "schema": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}},
                "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
            },
        },
        "properties": {
            "id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}},
            "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
        },
        "parameters": [],
        "defaults": {"wait_seconds": 0},
        "fixed": {},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
    "happyhorse_tasks_retrieve_batch": {
        "method": "POST",
        "path": "/happyhorse/tasks",
        "operation": "batch",
        "schema": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}, "minItems": 1},
                "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
            },
            "required": ["action", "ids"],
        },
        "properties": {
            "id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}, "minItems": 1},
            "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {"action": "retrieve_batch"},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
}
